#pragma once

#define SYSTICK_SR_CNTIF 0x01

#define SYSTICK_CTLR_ENABLE 0x01
#define SYSTICK_CTLR_INTEN 0x02
#define SYSTICK_CTLR_HCLK 0x04
#define SYSTICK_CTLR_AUTORE 0x08

#define PFIC_SCTLR_SLEEPDEEP 0x04
#define PFIC_SCTLR_WFITOWFE 0x08
#define PFIC_SCTLR_SEVONPEND 0x10
#define PFIC_SCTLR_SETEVENT 0x20

#define PWR_AWUEN 0x02
